
Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
  config.vm.synced_folder "./../", "/home/vagrant/dexter/", create: true
  end
  
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get update -y && 
    sudo apt-get upgrade -y &&
    sudo apt-get install -y \
      openjdk-8-jdk \
      clang-7 \
      g++ \
      libncurses5-dev \
      libncursesw5-dev \
      flex \
      bison \
      make \
      ant \
      libclang-7-dev

    sudo mv /usr/bin/java /usr/bin/java11
    sudo ln -s /usr/lib/jvm/java-8-openjdk-amd64/bin/java /usr/bin/java

    cd ~
    wget "https://people.csail.mit.edu/asolar/sketch-1.7.5.tar.gz"
    tar -xvzf sketch-1.7.5.tar.gz
    rm sketch-1.7.5.tar.gz
    mv sketch-1.7.5 ~/sketch
    cd ./sketch
    cd ./sketch-backend
    chmod +x ./configure
    ./configure
    make
    cd ~
    echo 'export PATH=$PATH:~/sketch/sketch-frontend' >> ~/.profile
    echo 'export SKETCH_HOME=~/sketch/sketch-frontend/runtime' >> ~/.profile

    wget https://github.com/halide/Halide/releases/download/v11.0.1/Halide-11.0.1-x86-64-linux-85c1b91c47ce15aab0d9502d955e48615f3bcee0.tar.gz
    tar xvf Halide-11.0.1-x86-64-linux-85c1b91c47ce15aab0d9502d955e48615f3bcee0.tar.gz
    rm ./Halide-11.0.1-x86-64-linux-85c1b91c47ce15aab0d9502d955e48615f3bcee0.tar.gz
    mv ./Halide-11.0.1-x86-64-linux ~/halide
    echo 'export PATH=$PATH:~/halide/bin' >> ~/.profile
    echo 'export CPATH=$CPATH:~/halide/include' >> ~/.profile
    echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/halide/lib' >> ~/.profile

    cd /home/vagrant/dexter/src/dexter/frontend/clang
    make
    cd ~/

    SHELL
  end
